# SPDX-FileCopyrightText: 2025 CybersunBot <cybersunbot@proton.me>
# SPDX-FileCopyrightText: 2025 Mnwa282 <167712034+Mnwa282@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: PrinterDocMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: document printer machine board
  description: A machine printed circuit board for an document printer
  components:
    - type: MachineBoard
      prototype: PrinterDoc
      stackRequirements:
        Manipulator: 4
        Glass: 1
