# Blob
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBlob
  name: Blob Role
  #  description: mind-role-blob-description
  components:
  - type: MindRole
    antagPrototype: Blob
    exclusiveAntag: true
  - type: BlobRole

# Flesh Cultists
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleFlesh
  name: Flesh Cultist Role
  #  description: mind-role-flesh-description
  components:
  - type: MindRole
    antagPrototype: FleshCultist
    exclusiveAntag: true
  - type: FleshCultistRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleFleshLeader
  name: Flesh Cultist Leader Role
  #  description: mind-role-flesh-description
  components:
  - type: MindRole
    antagPrototype: FleshCultistLeader
    exclusiveAntag: true
  - type: FleshCultistRole
    isLeader: true

# Changeling
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChangeling
  name: Changeling Role
  #  description: mind-role-changeling-description
  components:
  - type: MindRole
    antagPrototype: Changeling
    exclusiveAntag: true
  - type: ChangelingRole
