name: "Labels: Untriaged"

on:
  issues:
    types: [opened]

jobs:
  add_label:
    runs-on: self-hosted
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      if: join(github.event.issue.labels) == ''
      with:
        labels: "Status: Untriaged"
